### ISSUE TITLE
check dependencies

### ISSUE THREAD

**Issue by luxifer** [baptistedonaux/bipbip.js#2]
here https://github.com/baptistedonaux/bipbip.js/blob/master/lib/index.js#L10
you use `whereis` but the output of this command always display the command name you search ie:

```
whereis yolo
yolo:
```

I think it would be better to use `which` because when the command name you search does not exists, it outputs `<command> not found`. So a simple match on this pattern would do the job

**Comment by baptistedonaux** [comment]
`which` is better than `whereis`. I add this improvement in the next release. :+1:

**Comment by baptistedonaux** [comment]
Hey !

The new release use `which` !

Thank you for your suggestion !
